### PR TITLE
Parallelize vdaggarvindex

### PR DESCRIPTION
**Pull request by pittlerf**
Hi, I am working on performing the color summation first and then performing the summation over the spatial points. This version parallelize the vdaggerv computation not in "x" but in the indices of the vdaggerv itself.

### CODE REVIEW

**Comment by kostrzewa** [comment]
And is it any faster? Currently it fails the integration test.

**Comment by kostrzewa** [comment]
It does so, however, due to compilation errors as a result of missing namespace indications.

**Comment by pittlerf** [comment]
> It does so, however, due to compilation errors as a result of missing namespace indications.



> It does so, however, due to compilation errors as a result of missing namespace indications.

I am working on it, currently I am working on the error 

Eigen::Map<Eigen::MatrixXcd> Reshaped1(vnew.col(ncol).data(), 3, (V_t[i].col(ncol)).size()/3);

which actually in my separate toy C++ code works well

**Comment by kostrzewa** [comment]
@pittlerf is this abandoned and should the PR be closed?

**Pull request closed without merging**
