### PR TITLE
example input file for vdaggerv creation

### PR DESCRIPTION
**Pull request by pittlerf**

### CODE REVIEW

**Comment by kostrzewa** [comment]
Thanks, could you add some comments please?

**Comment by pittlerf** [comment]
> Thanks, could you add some comments please?

Yeah, sure, sorry that I have not done it yet.

**Comment by kostrzewa** [comment]
@pittlerf I've made a minor modif. Is the output_path actually required?

**Comment by pittlerf** [comment]
> @pittlerf I've made a minor modif. Is the `output_path` actually required?

Yes, I think that is required.

**Comment by kostrzewa** [comment]
Why is that?

**Comment by kostrzewa** [comment]
So we have:

```
void OperatorFactory::build_vdaggerv(const std::string &filename,
                                     const int config,
                                     const GlobalData &gd) {
  const ssize_t dim_row = 3 * Lx * Ly * Lz; 
  const int id_unity = operator_lookuptable.index_of_unity;

  // prepare full path for writing
  std::string const full_path =
      (boost::format("/%s/cnfg%04d/") % path_vdaggerv % config).str();

  // check if directory exists
  if ((handling_vdaggerv == "write") && (access(full_path.c_str(), 0) != 0)) {
    std::cout << "\tdirectory " << full_path.c_str()
              << " does not exist and will be created";
    boost::filesystem::path dir(full_path.c_str());
    if (!boost::filesystem::create_directories(dir))
      std::cout << "\tSuccess" << std::endl;
    else
      std::cout << "\tFailure" << std::endl;
  }
```

which means that only ```path_vdaggerv``` is actually required, correct?

**Comment by pittlerf** [comment]
> So we have:
> 
> ```
> void OperatorFactory::build_vdaggerv(const std::string &filename,
>                                      const int config,
>                                      const GlobalData &gd) {
>   const ssize_t dim_row = 3 * Lx * Ly * Lz; 
>   const int id_unity = operator_lookuptable.index_of_unity;
> 
>   // prepare full path for writing
>   std::string const full_path =
>       (boost::format("/%s/cnfg%04d/") % path_vdaggerv % config).str();
> 
>   // check if directory exists
>   if ((handling_vdaggerv == "write") && (access(full_path.c_str(), 0) != 0)) {
>     std::cout << "\tdirectory " << full_path.c_str()
>               << " does not exist and will be created";
>     boost::filesystem::path dir(full_path.c_str());
>     if (!boost::filesystem::create_directories(dir))
>       std::cout << "\tSuccess" << std::endl;
>     else
>       std::cout << "\tFailure" << std::endl;
>   }
> ```
> 
> which means that only `path_vdaggerv` is actually required, correct?

Ah, yes, that would require only for the contractions

**Pull request merged**
